### ISSUE TITLE
[DELETED]

### ISSUE THREAD

**Issue by amtlib-dot-dll** [v2ray/Planning#24]
[DELETED]

**Comment by S-Tsunemori** [comment]
I think this feature is more useful than this docker-related use-case. Being able to use DNS-over-HTTPS api of Google Public DNS maybe is **maybe the only way to get correct result** in areas can't access 8.8.8.8 directly.

The current suggested way of using Google Public DNS is redirect 8.8.8.8:53 to local using _Dokodemo-door_. It works but has a big flaw: some domains (mostly cdn services) would be resolved to an IP-address that is good for (v2ray)server but slow or even inaccessible for clients, due to the fact that server and client locate in a different geographical positions.

Surely you can access those sites through the proxy, then it will result in many unnecessary proxy accesses. On the other hand, using DNS-over-HTTPS API this problem can be solved by including ``edns_client_subnet`` parameter that points to the same subnet of client, so this cdn problem won't exist.

**Comment by DarienRaymond** [comment]
The edns_client_subnet feature is also available on UDP-based DNS query, right?

**Comment by DarienRaymond** [comment]
This issue will be fixed after https://github.com/v2ray/Planning/issues/27 gets fixed.
