### ISSUE TITLE
Use MUX to fetch data from mutiple server

### ISSUE THREAD

**Issue by testcaoy7** [v2ray/Planning#30]
It would be nice to have this feature...

If we can fetch data from mutiple server then we can achieve a very high link speed through link aggregation as well as enhance link stability.

In poor network condition, this feature can become very useful.

**Comment by xiaokangwang** [comment]
Could you please describe how should this function be implemented?
Only the server established connection with remote side can know what to send, and if this message were forwarded to other servers, clients would need to wait all servers to send their part before assembling  the data so that it can be send to programs.

**Comment by testcaoy7** [comment]
e.g：
1，A website contains 12 different pictures (pic1 to pic12)
2，We have 4 different v2ray server
3, v2ray client establishes connections to all the servers
4, each server fetchs 3 pictures at the SAME TIME
5, each server returns result to the client at the SAME TIME

However, it would up to users to choose servers which has similar latency to minimize the waiting time.

A lot cheap VPS has limited bandwidth (<100Mbps) and in Shanghai we even have 1000Mbps connection. It would be nice if we can aggregate mutiple VPS bandwidth.

**Comment by DarienRaymond** [comment]
This is not mux. This is basically load balancing such as #28 or #18
