### ISSUE TITLE
Vmess: Separate time difference error in log

### ISSUE THREAD

**Issue by astrataro** [v2ray/Planning#41]
Currently, if the client time differs from the server time, the server will log the error as "invalid user". It would be better to separate this from a real "invalid user" error, to make it easier for debugging, as well as for writing exclusive rules for log parsers like fail2ban.

**Comment by DarienRaymond** [comment]
It is not possible to tell such case. The authentication bytes in VMess are not decryptable. The server can't simply check whether the client uses the correct id, but just not proper timestamp. Otherwise it would be easy for attacker to intercept authentication messages and decrypt the id used by client.
